### ISSUE TITLE
Disabling Authentication

### ISSUE THREAD

**Issue by kri5** [driftluo/InfluxDBClient-rs#14]
It seems that you assume that Influxdb authentication mechanism will always be enabled, but it also can be disabled, and there is no way no to passe credentials, or even the ability to not pass the "u" and "p" arguments in the url.

Do you have any plans in supporting disabled authentication?

**Comment by driftluo** [comment]
Influxdb can disabled the authentication mechanism，but when I test on 1.01 version，even if disabled the authentication mechanism, push the user name and password will not be a problem, it seems to be directly ignored.

Does the current version fix this problem? If so, I will change it on my project.

**Comment by driftluo** [comment]
Next version, maybe 0.3.0, I want to support https, the Influxdbclient maybe like this:
```
struct InfluxdbClient {
    host: String,
    db: String,
    ssl: bool,
    username: Option<String>,
    passwd: Option<String>,
    read_timeout: Option<u64>,
    write_timeout: Option<u64>,
}
```
and user just need to provide such as localhost:8086.

I also want to support udp client(but it seems that there is little need for it) .

And I would like to refactor the code, it seems a bit messy now.

emm, but when to start doing this is a problem. : (
