### ISSUE TITLE
escape slash quote

### ISSUE THREAD

**Issue by Paxa** [driftluo/InfluxDBClient-rs#17]
if field value contain `\"` it will fail with error `SyntaxError("{error:unable to parse...`

Solution can be:
```rust
point.add_field("message", InflValue::String(message.replace("\\\"", "\\\\\"")));
```

**Comment by driftluo** [comment]
when I test on influxdb-1.0.2:
```rust
point1.add_field("quote", Value::String("\"fda".to_string()));
```
It works well, which version are you using?@Paxa

**Comment by Paxa** [comment]
I use 1.3.5

Just quote works well, but backslash + quote doesn't. Try:
```rust
point1.add_field("quote", Value::String("\\\"fda".to_string())); // value is \"fda
```

**Comment by driftluo** [comment]
Ok,  I know, I'll fix this bug right away, thank you

**Comment by Paxa** [comment]
Awesome! Thanks
