### ISSUE TITLE
Updated to use asynchronous io

### ISSUE THREAD

**Issue by driftluo** [driftluo/InfluxDBClient-rs#23]
[https://github.com/hyperium/hyper/issues/1443](https://github.com/hyperium/hyper/issues/1443)

Currently, hyper 0.12 is waiting for the release of futures 0.2. Tokio has explicitly supported the work-steal thread pool.

I also hope that this crate can use features to select whether the client uses asynchronous mode, that is say that support synchronous and asynchronous at the same time, the default synchronization mode.

However, currently, Rust/Cargo doesn't support two versions of a library at the same time, which makes it very difficult for me to do it. Maybe 2018-epoch [RFC](https://github.com/rust-lang/rfcs/pull/2126) can help me?

Maybe use reqwest? But it currently only supports uses system-native TLS....

Or wait for hyper 0.12 to give up sync mode directly?

**Comment by driftluo** [comment]
Oh, https://github.com/rust-lang/cargo/pull/6319 this can allow me use two versions of a library at the same time, so cool

**Comment by marcelbuesing** [comment]
futures 0.3 (alpha) support was just added to the master branch of hyper. E.g. see [this](https://github.com/hyperium/hyper/blob/master/examples/client.rs#L35) for an example of a client using Futures + await. I think it would be great to use this.
