### ISSUE TITLE
Chunked responses

### ISSUE THREAD

**Issue by miracle2k** [driftluo/InfluxDBClient-rs#26]
It seems the library currently does not support chunked responses. How would we go about implementing this? Should chunked responses be exposed to the user, or should chunked responses simply be merged?

Specifically, right now query returns a `Vec<Node>`. What we get from a server with chunked response we would be getting a data structure similar to `Vec<Vec<Node>>`, or possibly `Iter<Vec<Node>>`.

**Comment by driftluo** [comment]
I haven't paid much attention to the development of influxdb for a long time. I just looked at the api document and now support multiple query requests sent in one request. The return value is vec<vec<node>>. The current version does not support the request for multiple queries at once (it should be said that the return type is not supported). I will add it later. Is there any other place for the new version that does not support it? Or you can simply pull request to fix this support.

https://docs.influxdata.com/influxdb/v1.5/tools/api/#query
