### ISSUE TITLE
Target DB for UDP messages

### ISSUE THREAD

**Issue by AGutan** [driftluo/InfluxDBClient-rs#28]
I've checked the UDP example `tests/client_test.rs` and I found it a bit confusing.

Do UDP messages go to the "udp" and "telegraf" databases by default?
Or is there a way to specify where do the UDP messages go?

``` let mut udp = UdpClient::new("127.0.0.1:8089");
    udp.add_host("127.0.0.1:8090");
    let mut client = Client::default().set_authentication("root", "root");

    let mut point = point!("test");
    point.add_field("foo", Value::String(String::from("bar")));

    let _ = udp.write_point(point).unwrap(); // DOES THIS GO TO UDP/TELEGRAF BY DEFAULT?

    let _ = sleep(Duration::from_secs(1));
    client.switch_database("udp");
    let _ = client.drop_measurement("test").unwrap();
    client.switch_database("telegraf");
    let _ = client.drop_measurement("test").unwrap();

**Comment by driftluo** [comment]
When opening the udp port, the client sends something to the specified port. As soon as it is received, it directly creates the corresponding database and table in the database. This behavior has always been very confusing. I tested it in influxdb1.0.2.

**Comment by AGutan** [comment]
Ok got it. Thanks!
