### ISSUE TITLE
Deserialize to Value

### ISSUE THREAD

**Issue by michaelr524** [driftluo/InfluxDBClient-rs#32]
I'm querying and then putting back into the DB a subset of the results set. So for my use case it makes sense to get the results from the DB in the same type as used to insert records into the DB.
I wonder if it would make sense to have this:
https://github.com/driftluo/InfluxDBClient-rs/blob/master/src/keys.rs#L141
Deserialize to this directly:
https://github.com/driftluo/InfluxDBClient-rs/blob/master/src/keys.rs#L9
Instead of using the JSON serde Value type?

**Comment by driftluo** [comment]
Yeah, it is true that it can be done here.

But if I do this, it need to upgrade to 0.4. At present, the practice of 0.4 is not very sure, so even if I change it now, I will not directly publish it to crate.

For now, you can write a fuction to convert，I am very sorry about this.
