### ISSUE TITLE
Feature to skip loging of points who's values have not changed?

### ISSUE THREAD

**Issue by gilescope** [driftluo/InfluxDBClient-rs#33]
To reduce the amount of points we're entering into influx_db one could only send a point (identified by set of tag values) if any of the values are different to last time a point was sent.

I'm thinking others will need this also - this seems pretty generic functionality? Is there already functionality to do this? If not I can take a stab at a PR and we can take it from there.

**Comment by driftluo** [comment]
I may not understand what you mean. 

In my impression, influxdb receives data with exactly the same time and tag, then it will overwrite the previous data by itself.

The benefit of judging whether the data is the same on the client side may be to reduce the interaction time, but there will be a large cache that needs to be stored. Is this too heavy for the client SDK?

**Comment by gilescope** [comment]
If the only update since the previous time would be the 'time' then don't bother sending anything.

If the set of tags/fields doesn't change very often but you send many updates then the cache size stays small. Also if we're not recording the same value at many different time instances that should reduce the storage costs for influxdb.

One could combine it with a datetime of last time the point was sent over to influxdb so that even if the numbers stay the same it's updated once every X time period.

Is this a little clearer as to the usecase?

**Comment by driftluo** [comment]
In most cases, influxdb exists as a backend data store for a monitoring system.

There are many heartbeat signals in the monitoring system, the heartbeat signal is only a new timestamp.

Because in the heartbeat interval, in fact other data is not updated.

If the data is not sent by default, the consequence is that the user is very confused.

**Comment by gilescope** [comment]
That's fine. If no one else needs this functionality we'll keep it in-house.

**Comment by driftluo** [comment]
If you really want to do it, you can make a configuration or a feature, it shouldn't be the default behavior.

I am not sure if anyone needs this feature and whether this feature is too heavy for a sdk
