### ISSUE TITLE
new panics

### ISSUE THREAD

**Issue by gilescope** [driftluo/InfluxDBClient-rs#34]
```rust
pub fn new<T: Into<String>>(address: T) -> Self {
        UdpClient {
            hosts: vec![address.into().to_socket_addrs().unwrap().next().unwrap()],
        }
    }
```
If the hostname isn't resolvable then the udp client panics on unwrap(). 
It would be great if new returned a Result instead (or alternatively had a try_new fn).

## Workaround:

match against address.into().to_socket_addrs() and check that doesn't error first before calling new.

**Comment by driftluo** [comment]
https://github.com/driftluo/InfluxDBClient-rs/blob/24740b3161dfe9cfc1dd6cc78b0873ac8eb3e741/src/client.rs#L596

Docs already explained, if it can't be converted, it will panic

**Comment by gilescope** [comment]
Yeah, I just didn't want to catch a panic in my code.

**Comment by driftluo** [comment]
> Yeah, I just didn't want to catch a panic in my code.

I can only say that your thoughts are too naive. In the standard library, panic is normal when the memory cannot be allocated.

ref: https://doc.rust-lang.org/src/alloc/raw_vec.rs.html#83

### Here is my personal opinion of panic:
If a key structure initialization cannot be done, there are two ways to deal with it:
1. return Result(***will warning on Clippy check***)/Option, etc. 
2. panic

These are all means to prevent further spread of errors. 

If the document does not have the possibility of writing panic, it is panic directly. That is the problem of the library. 

If it is written, the caller does not pay attention. I think this is not a problem in the library.

If this is a binary repo, panic behavior is not allowed regardless of what the user enters.

There are still many assumptions in this library, for example, suppose the caller knows that this library uses the standard IP protocol and cannot pass unresolved URI information in the host. This assumption also exists in `httpclient`.

Let me think about it, emmm, I think users should be able to understand the appeal question. However, it may indeed require some repairs to make this library more robust.

**Comment by rnestler** [comment]
In my opinion, in libraries stuff that can go wrong during run-time which are not necessarily programmer errors or unrecoverable like allocation errors, shouldn't cause panics.
In an application the address to connect to may come from end-user input like command line flags or environment variables, so it should be easy for a user of the library to handle the error properly to print a nice error message for the end-user.
So for this specific case I guess returning a `Result` would indeed be nicer :slightly_smiling_face:

**Comment by juchiast** [comment]
I suggest changing the function to receive SocketAddr directly.
