### ISSUE TITLE
Unable to use GROUT BY statement

### ISSUE THREAD

**Issue by gmg137** [driftluo/InfluxDBClient-rs#40]
When I try to query with the GROUP BY statement, I always return the following error, but I have no problem with the same statement query in the CLI.
```rust
    let sql = format!(
        "select SPREAD(imp) from zydl_01_1 where time > '{}' AND time < '{}'",
        start.to_rfc3339(),
        end.to_rfc3339()
    );
    let q = influxdb.query(&sql, Some(Precision::Seconds)).await;
```
This will return "data did not match any variant of untagged enum Value at line 1 column 115"

**Comment by driftluo** [comment]
I know what the problem is, this is my mistake, I did not consider the problem of the combination of return values, I fixed it immediately

**Comment by driftluo** [comment]
@gmg137 You can try this branch https://github.com/driftluo/InfluxDBClient-rs/pull/41 and_then publish a new version

**Comment by gmg137** [comment]
非常感谢！刚发现作者原来是杭州的。

话说有没有考虑兼容async-std异步运行时？我拉取了一个分支，使用 isahc 做 http 客户端，可以兼容tokio 和 async-std，不过 isahc 不是纯 rust 实现的。

________________________________
发件人: 漂流 <notifications@github.com>
发送时间: 2020年6月2日星期二 下午12:05
收件人: driftluo/InfluxDBClient-rs
抄送: gmg137; Mention
主题: Re: [driftluo/InfluxDBClient-rs] Unable to use GROUT BY statement (#40)


@gmg137<https://github.com/gmg137> You can try this branch #41<https://github.com/driftluo/InfluxDBClient-rs/pull/41> and_then publish a new version

―

**Comment by driftluo** [comment]
目前其实理论上是支持的, async-std 依赖了 [smol](https://github.com/async-rs/async-std/blob/master/Cargo.toml#L45)，但很怪异的是，它竟然不能开 tokio 的 feature，迷惑操作，如果能开的话就可以支持了。

反过来讲，如果要库支持的话，得用一个不依赖运行时的 http 库或者自己写一套，自己造轮子的事情在社区有库的情况下一般不太有动力（

**Comment by gmg137** [comment]
reqwest 直接依赖 tokio，貌似也不打算兼容 async-std。看来只能等 smol 一统江湖了
