### ISSUE TITLE
Is it possible to use library in multiprocessing?

### ISSUE THREAD

**Issue by matvey-istomin** [driftluo/InfluxDBClient-rs#44]
I tried to speed up writing points using threadpool. But not at all points is written. 

    let n_workers = 4;
    thread_local!(static CLIENT: Client = Client::new(Url::parse("http://localhost:8086").expect("Cannot parse url"), "data") );
    let pool = ThreadPool::new(n_workers);

    for chunk in data.chunks(60000) {
        let points = Points::create_new(chunk.to_vec());
        pool.execute(move || {
            CLIENT.with(|c| {
                tokio::runtime::Runtime::new().unwrap().block_on(async move {
                    c.write_points(points, Some(Precision::Seconds), None).await.expect("Cannot write points");
                });
            });
                // CLIENT.write_points(points, Some(Precision::Milliseconds), None).await.expect("Cannot write points");
        });
        
    }
Why did this happen?

**Comment by driftluo** [comment]
Your code shocked me. . .

Before you write, you need to understand a few things：
1. What is asynchronous？
2. What is tokio？

After that, you can start writing code

**Comment by matvey-istomin** [comment]
Mmm.. yeah. I'm noob in Rust so it looks like I'm asking a stupid questions.
1. Asynchronous is when you have some tasks and most part of time is waiting but while some task is waiting you want to switch to another task.
2. Tokio is library for writing asynchronous apps.
I also tried to write that and it executes faster but it also causes lags. 
    

    let coros = vec![];
    for chunk in rib.data.chunks(70000) {
            let points = Points::create_new(chunk.to_vec());
            corors.push(client.write_points(points, Some(Precision::Seconds), None));   
    }
   
    tokio::runtime::Runtime::new().unwrap().block_on(async move { 
         futures::future::join_all(coros).await;
    });

**Comment by driftluo** [comment]
```rust
let mut handles = Vec::new();
let rt = tokio::runtime::Runtime::new().unwrap();
let c = Client::new(Url::parse("http://localhost:8086");
for chunk in data.chunks(60000) {
    let points = Points::create_new(chunk.to_vec());
    let task = c.write_points(points, Some(Precision::Seconds), None);
    let handle = rt.spawn(async move {
      task.await.expect("Cannot write points");
    });
    handles.push(handle);
}
rt.block_on(async move { 
     futures::future::join_all(handles).await;
 });   
```
Write like this, in theory, it will be faster, each write is a different task

**Comment by matvey-istomin** [comment]
It really works faster. Thanks.
