### ISSUE TITLE
Add Token-based authentication

### ISSUE THREAD

**Issue by hpux735** [driftluo/InfluxDBClient-rs#45]
I see that you can set_authentication using a username and password.  But, in many cases an authentication token is preferred.

**Comment by driftluo** [comment]
https://docs.influxdata.com/influxdb/v1.8/administration/authentication_and_authorization/#3-include-the-token-in-http-requests

Are you talking about this kind of jwt token? This is very simple, you only need to add an interface.

This seems to be a newly added feature, there was no such authentication method in the previous version

**Comment by hpux735** [comment]
Hi, thanks for responding.  

It's not a JWT, exactly, it's more like a password than anything.

I think the confusion I'm having is that it looks like this library is created against the 1.x API version, and tokens are preferred in 2.0.

https://docs.influxdata.com/influxdb/v2.0/reference/api/#authentication

For convenience:
```
curl --request POST \
  --url http://localhost:8086/api/v2/write?org=my-org&bucket=example-bucket \
  --header 'Authorization: Token YOURAUTHTOKEN'
```

I'm _brand new_ at Rust, and I'm starting on a project that needs Influx 2.0.  I'm happy to add it myself, and I've started a fork.  I'm just trying to gauge how much this is going to be while also learning Rust :)

**Comment by driftluo** [comment]
2.x influx is not stable yet, and I'm not focusing on the beta version to see the specific changes yet!

**Comment by hpux735** [comment]
That makes sense.  They do seem to be getting ahead of themselves.  They're pushing people to 2.0 in their sales work already, and it seems like it's probably time for them to commit.  

We can go ahead and call this resolved with the JWT token addition, and I'll wait for 2.0, I suppose
