### ISSUE TITLE
character 'i' added on integer serilization

### ISSUE THREAD

**Issue by ChrisCA** [driftluo/InfluxDBClient-rs#47]
I assume that this is an artefact from early development.
![grafik](https://user-images.githubusercontent.com/4296262/95712979-0bda8580-0c66-11eb-918a-4e939b0106a6.png)
This causes wrong integer inputs.

**Comment by driftluo** [comment]
https://docs.influxdata.com/influxdb/v1.8/write_protocols/line_protocol_reference/#data-types
> Signed 64-bit integers (-9223372036854775808 to 9223372036854775807). Specify an integer with a trailing i on the number. Example: 1i.

**Comment by ChrisCA** [comment]
In my understanding, this does not apply here.
I'm talking about a "tag set" and not about a "measurement".

Right above your quoted line, tags are defined as string only, while measurement values allow the other data types.
For the measurement data types I agree that on a signed integer a trailing 'i' is specified but for tags, there should actually not integer type being allowed.
My assumption was that when choosing an integer type on a tag the integer value is simply stringified, but when this happened its not just stringified but handled like it would be a measurement value so stringified + trailing 'i'.

In my opinion it should be either only string types being allowed to be used with tags which means the lib user would need to stringify or the string conversion should be separate, once for a measurement value and once for tags.

**Comment by driftluo** [comment]
Oh, I see, the tag value is just a string, it should not be consistent with the type of the data value
