### ISSUE TITLE
Response Decoding Error: SHOW query does not contain name, but client lib expects it

### ISSUE THREAD

**Issue by Darneas** [driftluo/InfluxDBClient-rs#53]
We are using this library to query an [influx db version 1.8. container](https://github.com/influxdata/influxdata-docker/blob/6f10af34465b675d9e6de241b57210f01d12b453/influxdb/1.8/Dockerfile).

When running `client.query("SHOW RETENTION POLICIES ON database", None)` the HTTP response looks as follows:

```json
{
    "results": [
        {
            "statement_id": 0,
            "series": [
                {
                    "columns": [
                        "name",
                        "duration",
                        "shardGroupDuration",
                        "replicaN",
                        "default"
                    ],
                    "values": [
                        [
                            "autogen",
                            "0s",
                            "168h0m0s",
                            1,
                            false
                        ],
                        [
                            "online_policy",
                            "8736h0m0s",
                            "168h0m0s",
                            1,
                            true
                        ]
                    ]
                }
            ]
        }
    ]
}
```

The field `name` is missing which seems to be correct behaviour. However, this library expects it to be present and panics with:

`Err(Communication("error decoding response body: missing field 'name' at line 1 column 208"))`

If we are not mistaken, this is due to this line and serde trying to match this: https://github.com/driftluo/InfluxDBClient-rs/blob/a89189bcf7d190c4be24039ffb0058b5966fa6ad/src/keys.rs#L135

Don't know much about `serde` but probably one can define the field as optional like I did [here](https://github.com/Darneas/InfluxDBClient-rs/blob/darneas-53-optional-name/src/keys.rs#L135)? Unfortunately, this would be a breaking change as `pub name: String` changes. Let me know if you would be interested in a pull request.

**Comment by driftluo** [comment]
I'm thinking whether it is necessary to add the serde default option to the current version so that if it is empty, serde can give an empty string field out so that the current version does not break 

Of course, the current library will soon undergo a breaking change, because it needs to be upgraded to tokio 1.x version, but I did not think about whether to add support for 2.x protocol support in this version, because this will be a not short development time

**Comment by driftluo** [comment]
@Darneas pull request please, I decided to use serde default tag in the current version and `Option` in the next break version(tokio 1.x)

**Comment by Darneas** [comment]
@driftluo: Fine, I opened one here https://github.com/driftluo/InfluxDBClient-rs/pull/54.

Please be aware that I also had to make `values` optional as there is another query that does not have values. The default tag way would then probably be an empty `Vec`.

**Comment by driftluo** [comment]
thanks for your help
