### ISSUE TITLE
v2 support?

### ISSUE THREAD

**Issue by GopherJ** [driftluo/InfluxDBClient-rs#57]
Hi, I came across this lib, thanks for your work! I have some questions: 

1. Does it support influxdb v2?
2. Will influxdb v2 be supported?

**Comment by driftluo** [comment]
The current library does not support the v2.x version of influxdb

I haven't started to see the changes in v2.x, and I seem to find that the official v2 version of the client is being provided. Maybe I don’t need to do it again?

**Comment by GopherJ** [comment]
yes I found this https://github.com/influxdata/influxdb_iox/tree/main/influxdb2_client I'll try it to see if it works
